# Generated by Django 3.0 on 2020-12-04 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DamageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen_name', models.CharField(max_length=50)),
                ('citizen_address', models.CharField(max_length=100)),
                ('citizen_phone_number', models.CharField(max_length=20)),
                ('damage_type', models.CharField(max_length=30)),
                ('dollar', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=50)),
                ('equipment_number', models.IntegerField(default=0)),
                ('equipment_price', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Potholes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=80)),
                ('size', models.IntegerField()),
                ('location', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=50)),
                ('repair_priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RepairCrew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_people', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_applied', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('filter_material', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('equipment_assigned', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.Equipment')),
                ('potholes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='models.Potholes')),
                ('repair_crew', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='models.RepairCrew')),
            ],
        ),
    ]
