# Generated by Django 3.0 on 2020-12-04 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damagefile',
            name='damage_type',
        ),
        migrations.RemoveField(
            model_name='damagefile',
            name='dollar',
        ),
    ]
