# Generated by Django 3.0 on 2020-12-04 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20201204_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagefile',
            name='potholes',
            field=models.OneToOneField(default=12, on_delete=django.db.models.deletion.CASCADE, to='models.Potholes'),
            preserve_default=False,
        ),
    ]
