# Generated by Django 3.0 on 2020-12-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_damagefile_potholes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='filter_material',
            field=models.CharField(default='Nothing', max_length=50),
        ),
    ]
