# Generated by Django 3.0 on 2020-12-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_auto_20201204_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='cost',
            field=models.IntegerField(default=10),
        ),
    ]
