# Generated by Django 3.0 on 2020-12-04 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20201204_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='damagefile',
            old_name='potholes',
            new_name='pothole',
        ),
        migrations.RenameField(
            model_name='workorder',
            old_name='potholes',
            new_name='pothole',
        ),
    ]
