# Generated by Django 3.0 on 2020-12-11 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_auto_20201204_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_number',
        ),
        migrations.AddField(
            model_name='repaircrew',
            name='equipments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='models.Equipment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repaircrew',
            name='isBusy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repaircrew',
            name='leader',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
