# Generated by Django 3.0 on 2020-12-11 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_auto_20201211_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potholes',
            name='repair_priority',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='cost',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='filter_material',
            field=models.CharField(blank=True, default='Nothing', max_length=50),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='hours_applied',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='repair_crew',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='models.RepairCrew'),
        ),
    ]
