# Generated by Django 3.0 on 2020-12-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_auto_20201211_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potholes',
            name='repair_priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
