# Generated by Django 3.0 on 2020-12-11 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_auto_20201211_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repaircrew',
            name='equipments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='models.Equipment'),
        ),
    ]
