# Generated by Django 3.0 on 2020-12-11 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0014_auto_20201211_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='repair_crew',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='models.RepairCrew'),
        ),
    ]
